.TH "ACRID" "1" "2021-06-02" "Geek Central" "PDF Hacks"

.SH NAME
acrid - examine/manipulate metadata in a PDF file.

.SH SYNOPSIS
.B acrid
.RI [ options "...] " cmd
.IR file ...

.SH DESCRIPTION
.B acrid
is a command-line tool for examining and changing the contents of the
.B Info
dictionary in a PDF file. Entries can be added or removed, or
their associated values changed. There is also an option to delete
the XMP data.

.SH SUBCOMMANDS
The operation to perform depends on
.IR cmd ,
as do the valid associated
.IR options ,
as follows:

.TP
\fBhelp\fR [\fIcmd\fR]
with
.IR cmd ,
displays help for the specified command. If
.I cmd
is omitted, shows a list of valid commands.

.TP
\fBsetinfo\fR [\fIoptions\fR...] \fIin-pdf-file out-pdf-file\fR
Reads
.IR in-pdf-file ,
makes changes to the metadata as specified by the options, and saves
the changed file as
.IR out-pdf-file .
Valid
.I options
are:

.RS 4

.TP
.B --allow-nonstd
Without this option, the only
.IR keyword s
that can be specified to the
.B --set
and
.B --del
options are
.BR Author ", " CreationDate ", " Creator ", " Keywords ", " ModDate ", " Producer ", " Subject ", " Title
and
.BR Trapped .
Specifying this option allows you to include your own nonstandard keywords as well.

.TP
.B --delall
Deletes all keys in the
.B Info
dictionary. If specified together with
.BR --set ,
then the deletions are done first, then the
.B --set
options are performed to put back the specified keys.

.TP
.B --delxmp
Deletes any XMP metadata, if this is present. The presence of XMP data is
supposed to override the
.B Info
dictionary and be a replacement for it, so if you are making changes to the
.BR Info ,
getting rid of the XMP data is probably a good idea.

.TP
.BI --del= keyword
Deletes the
.B Info
entry with the specified
.IR keyword .
May be specified more than once to delete multiple
.IR keyword s
in a single operation.

.TP
.BI --set= keyword = value
Sets the
.B Info
entry with the specified
.I keyword
to the specified
.IR value .
Adds such an entry with that
.I keyword
if there isn’t one already, or replaces an existing
entry if there is one. May be specified more than once to set/add multiple
.IR keyword s
in a single operation.
.RE

.TP
\fBshowinfo\fR \fIin-pdf-file\fR
Shows the current info from the specified PDF file, including a dump of the
XMP data, if present.

.SH NOTES

Requires the
.UR https://github.com/pikepdf/pikepdf
pikepdf
.UE
toolkit.

.SH BUGS

According to the latest PDF specs, XMP metadata is supposed to be a replacement
for the
.B Info
dictionary, which is now deprecated.

.SH EXAMPLES

.RS 4
acrid showinfo fred.pdf
.RE

Displays any
.B Info
and XMP data for the file
.BR fred.pdf .

.RS 4
.nf
acrid setinfo --delxmp --set=Author=\(dqFred Dagg\(dq \e
.RS 4
--set=Creator=\(dqNot LibreOffice\(dq --del=Producer \e
fred.pdf dagg.pdf
.RE
.fi
.RE

Copies
.B fred.pdf
to
.BR dagg.pdf ,
getting rid of any XMP data, setting the
.B Author
and
.B Creator
fields of the
.B Info
dictionary and deleting any
.B Producer
entry (if present) in the process.
